apiVersion: v2
appVersion: master
description: |
  Detects hardware features available on each node in a Kubernetes cluster, and advertises
  those features using node labels.
name: node-feature-discovery
sources:
 - https://github.com/kubernetes-sigs/node-feature-discovery
home: https://github.com/kubernetes-sigs/node-feature-discovery
keywords:
  - feature-discovery
  - feature-detection
  - node-labels
type: application
version: 0.2.1
dependencies:
  - name: spire
    version: 0.24.1
    repository: https://spiffe.github.io/helm-charts-hardened/
    condition: spire.enabled
